// Generado automáticamente — no editar manualmente
// Editar el archivo traducciones.csv y volver a convertir

const TRADUCCIONES = {
  "es": {
    "log": {
      "noEsTuTurno": "No es tu turno",
      "mulliganPrimero": "Primero hay que resolver el mulligan",
      "soloMulligan": "Sólo puedes devolver cartas durante el mulligan",
      "seleccionaCarta": "Selecciona una carta primero",
      "seleccionaCartaMulligan": "Selecciona una carta para devolver al mazo",
      "cartaSeleccionadaCampo": "Carta seleccionada: {carta}",
      "mulliganYaConfirmado": "El mulligan ya ha sido confirmado",
      "noEsFase": "No es fase de {zona}",
      "noEsFaseRecepcion": "No es fase de recepción",
      "noEsFasePase": "No es fase de pase",
      "noEsFaseRemate": "No es fase de remate",
      "noEsFaseBloqueo": "No es fase de bloqueo",
      "noCartaEnZona": "No has jugado ninguna carta este turno en {zona}",
      "eventoUsarBoton": "Los eventos se juegan con el botón Jugar Evento",
      "zonaProhibida": "{carta} no puede jugar en {zona}",
      "cartaDuplicada": "Ya has jugado a {carta} este turno",
      "noColocador": "No puedes colocar un colocador (S) este turno",
      "yaHayCartaEnZona": "Ya hay una carta en {zona}",
      "cartaColocadaEn": "{jugador} juega a {carta} en {zona} ({stat})",
      "noReceptorAlto": "No puedes colocar un receptor con recepción de 6 o más este turno",
      "sinCartasEnMazo": "{jugador} no tiene más cartas en el mazo",
      "robarCartas": "{jugador} roba {cantidad} carta(s)",
      "gutsInsuficiente": "No hay suficientes cartas en la zona de GUTS indicada",
      "gutsInsuficienteMultiZona": "No hay suficientes GUTS en el campo (necesitas {cantidad}, tienes {total})",
      "gutsUsado": "GUTS usado correctamente en {zona}",
      "gutsMultiZona": "GUTS: {cantidad} cartas enviadas al trash",
      "gutsTitulo": "GUTS en {zona}: Descarta ( {actual} / {total} )",
      "cartaEnGuts": "Esta carta está en el GUTS y no puede usar su habilidad",
      "sinHabilidad": "Esta carta no tiene habilidad",
      "habilidadYaUsada": "Esta habilidad ya fue usada",
      "noEsEvento": "Esta carta no es un evento",
      "eventoFaseIncorrecta": "No puedes jugar este evento en fase de {zona}",
      "eventoJugado": "{jugador} juega el evento: {carta}",
      "eventoEnMano": "Necesitas una carta de evento en la mano",
      "eventoPagar": "Carta de evento enviada al trash como coste",
      "cartaUnica": "Ya has jugado una carta de {carta} este turno",
      "sacaConPotencia": "{carta} saca con una potencia de {valor}",
      "paseConPotencia": "{carta} realiza un pase con una potencia de {valor}",
      "remataConPotencia": "{carta} remata con una potencia de {valor}",
      "recepcionVsAtaque": "Recepción: {recepcion} vs Ataque: {ataque}",
      "buenaRecepcion": "{carta} recibe con una potencia de {valor} = Buena recepción",
      "recepcionFallida": "{carta} recibe con una potencia de {valor} = Recepción fallida",
      "puntoParaRival": "Punto para {jugador}",
      "defensaTotal": "Bloqueo total: {valor}",
      "bloqueoExitoso": "Bloqueo exitoso",
      "bloqueoFallido": "Bloqueo insuficiente",
      "mulliganConfirmado": "{jugador} confirma el mulligan",
      "mulliganRival": "Mulligan de {jugador} — devuelve las cartas que no quieras y confirma",
      "partidaIniciada": "¡Partida iniciada! Saca {jugador}",
      "pierdePartida": "{jugador} no tiene cartas en su mazo de puntos. ¡Ha perdido el partido!",
      "pierdeUnPunto": "{jugador} pierde un punto y roba una carta de su mazo de puntos. Le quedan {cantidad}",
      "cartaDevuelta": "{carta} devuelta al mazo",
      "concedePunto": "{jugador} concede el punto",
      "efectoActivo": "Efecto activo: {tipo}",
      "potenciarReceptor": "Efecto potenciar receptor: +{valor} a la recepción de {carta}",
      "potenciarColocador": "Efecto potenciar colocador: +{valor} al pase de {carta}",
      "potenciarRematador": "Efecto potenciar rematador: +{valor} al remate de {carta}",
      "potenciarReceptorEscuela": "Efecto activo: receptores{escuela} tendrán +{valor} a la recepción",
      "potenciarColocadorEscuela": "Efecto activo: colocadores{escuela} tendrán +{valor} al pase",
      "potenciarRematadorEscuela": "Efecto activo: rematadores{escuela} tendrán +{valor} al remate",
      "potenciarPersonajeActivo": "Efecto activo: {nombre} tendrá +{valor} en {zona} este turno",
      "potenciarPersonaje": "Efecto: +{valor} en {zona} de {nombre}",
      "efectoDebilitarReceptor": "Efecto: -{valor} a la recepción de {carta}",
      "efectoDebilitarColocador": "Efecto colocador debilitado: -{valor} al pase de {carta}",
      "efectoDebilitarRematador": "Efecto rematador debilitado: -{valor} al remate de {carta}",
      "efectoDebilitarBloqueo": "Efecto: -{valor} al bloqueo de {carta}",
      "debilitarRematadorActivo": "Efecto activo: el próximo rematador rival tendrá -{valor} al remate",
      "debilitarColocadorActivo": "Efecto activo: el próximo colocador rival tendrá -{valor} al pase",
      "debilitarReceptorActivo": "Efecto activo: el próximo receptor rival tendrá -{valor} a la recepción",
      "debilitarBloqueadorCentralActivo": "Efecto activo: el próximo bloqueador central rival tendrá -{valor} al bloqueo",
      "efectoTendo": "Efecto Tendo: el rival robará 1 carta cada vez que añadas una carta a tu mano",
      "blockoutActivo": "Efecto activo: los bloqueadores rivales con bloqueo igual o menor a {valor} irán al trash",
      "blockout": "Blockout: {carta} tiene bloqueo igual o menor a {valor} y va al trash",
      "efectoBloqueoOfensivo": "Efecto de Bloqueo Ofensivo ({valor}): si el bloqueo es exitoso el contraataque tendrá una potencia de {valor}",
      "anularBloqueadorCentralActivo": "Efecto activo: el bloqueador central rival tendrá su bloqueo anulado",
      "anularBloqueadorCentral": "Efecto activo: bloqueo del bloqueador central anulado",
      "negarBloqueadoresApoyoActivo": "Efecto activo: el rival solo podrá colocar el bloqueador central este turno",
      "negarBloqueadoresApoyo": "No puedes colocar bloqueadores de apoyo este turno",
      "negarReceptorAltoActivo": "Efecto activo: el rival no podrá colocar un receptor con recepción original de 6 o más",
      "negarReceptorAlto": "No puedes colocar un receptor con recepción de 6 o más este turno",
      "negarColocadorActivo": "Efecto activo: el rival no podrá colocar un colocador el próximo turno",
      "negarColocador": "No puedes colocar un colocador este turno",
      "negarOneTouchActivo": "Efecto activo: el rival no podrá usar One Touch en su próximo bloqueo",
      "negarOneTouch": "One Touch negado por habilidad del rival",
      "negarCartaDesdeManoActivo": "Efecto activo: el rival no podrá usar habilidades desde la mano en {fases}",
      "negarCartaDesdeMano": "No puedes usar habilidades desde la mano en {fases}",
      "negarEventosActivo": "Efecto activo: el rival no podrá jugar eventos de {fase}",
      "negarEventos": "No puedes jugar eventos de {fase} este turno",
      "negarRobar": "Efecto activo: {jugador} no puede robar cartas por habilidad este turno",
      "anularHabilidadReceptorActivo": "Efecto activo: el siguiente receptor rival no podrá usar su habilidad",
      "anularHabilidadReceptor": "El receptor no puede usar su habilidad este turno",
      "anularHabilidadColocador": "Efecto activo: el colocador no puede usar su habilidad",
      "limitarBloqueadoresActivo": "Efecto activo: el rival solo podrá colocar hasta {max} bloqueadores",
      "limitarBloqueadores": "No puedes colocar más de {max} bloqueadores este turno",
      "maximoBloqueadores": "Máximo 2 bloqueadores de apoyo",
      "bloqueoMinimoActivo": "Efecto activo: el bloqueo rival fallará si su defensa total es {valor} o menos",
      "bloqueoMinimo": "Efecto de bloqueo mínimo: bloqueo insuficiente forzado",
      "oneTouch": "One Touch ({valor}): -{valor} al ataque rival. Ataque actual: {ataque}",
      "bloqueoOfensivo": "Bloqueo ofensivo: el contraataque tiene potencia {valor}",
      "mazoPuntosPreparado": "{jugador}: mazo de puntos preparado con 2 cartas",
      "cartaColocadaBloqueo": "{jugador} juega a {carta} como {tipo} ({stat})",
      "bloqueadorCentral": "Bloqueador central",
      "apoyoBloqueo": "Bloqueo de apoyo",
      "soloDesdeMano": "Esta carta solo puede usar su habilidad desde la mano",
      "noHabilidadMano": "Esta carta no tiene habilidad de mano",
      "noHabilidadEnFase": "No puedes usar esta habilidad en fase de {zona}",
      "finta": "Finta: el ataque queda fijado en {valor}. Se salta la fase de bloqueo",
      "robarCuandoRival": "El rival roba 1 carta por efecto",
      "robarCuandoRivalActivo": "Efecto activo: el rival robará 1 carta cada vez que añadas una carta a tu mano",
      "negarRobarActivo": "Efecto activo: el rival no podrá robar cartas mediante habilidades el próximo turno",
      "sinCartasValidas": "No hay cartas válidas en la búsqueda",
      "esperandoDescarte": "Esperando que el rival descarte una carta",
      "descartarCuandoRoboActivo": "Efecto activo: el rival deberá descartar 1 carta cada vez que añada una carta a su mano por medios no estándar",
      "cartaColocadaComoRematador": "{carta} colocado como rematador con +{valor} al remate",
      "habilidadActivada": "Habilidad de {carta} activada",
      "condicionNoCumplida": "Condición no cumplida",
      "condicionCumplida": "Condición adicional cumplida. Efecto activado",
      "cartaDescartadaCoste": "{carta} descartada como coste",
      "cartaRevelada": "Carta revelada: {carta}",
      "cartasAlFondoMazo": "Cartas restantes enviadas al fondo del mazo",
      "motivar": "Motivación: robas 1 carta extra por el punto del rival",
      "motivarActivo": "Efecto activo: si el rival pierde un punto en el siguiente turno, robas 1 carta extra"
    }
  },
  "en": {
    "log": {
      "noEsTuTurno": "Is not your turn",
      "mulliganPrimero": "Mulligan must be resolved first",
      "soloMulligan": "You can only return cards during mulligan",
      "seleccionaCarta": "Select a card first",
      "seleccionaCartaMulligan": "Select a card to return to the deck",
      "cartaSeleccionadaCampo": "Card selected: {carta}",
      "mulliganYaConfirmado": "Mulligan already confirmed",
      "noEsFase": "Not the {zona} phase",
      "noEsFaseRecepcion": "Not the reception phase",
      "noEsFasePase": "Not the set phase",
      "noEsFaseRemate": "Not the spike phase",
      "noEsFaseBloqueo": "Not the block phase",
      "noCartaEnZona": "No card played this turn in {zona}",
      "eventoUsarBoton": "Events are played with the Play Event button",
      "zonaProhibida": "{carta} cannot play in {zona}",
      "cartaDuplicada": "You already played {carta} this turn",
      "noColocador": "You cannot place a setter (S) this turn",
      "yaHayCartaEnZona": "There is already a card in {zona}",
      "cartaColocadaEn": "{jugador} plays {carta} in {zona} ({stat})",
      "noReceptorAlto": "You cannot place a receiver with reception 6 or more this turn",
      "sinCartasEnMazo": "{jugador} has no more cards in the deck",
      "robarCartas": "{jugador} draws {cantidad} card(s)",
      "gutsInsuficiente": "Not enough cards in the indicated GUTS zone",
      "gutsInsuficienteMultiZona": "Not enough GUTS on the field (need {cantidad}, have {total})",
      "gutsUsado": "GUTS used correctly in {zona}",
      "gutsMultiZona": "GUTS: {cantidad} cards sent to discard",
      "gutsTitulo": "GUTS in {zona}: Discard ( {actual} / {total} )",
      "cartaEnGuts": "This card is in the GUTS and cannot use its ability",
      "sinHabilidad": "This card has no ability",
      "habilidadYaUsada": "This ability was already used",
      "noEsEvento": "This card is not an event",
      "eventoFaseIncorrecta": "You cannot play this event in {zona} phase",
      "eventoJugado": "{jugador} plays the event: {carta}",
      "eventoEnMano": "You need an event card in hand",
      "eventoPagar": "Event card sent to discard as cost",
      "cartaUnica": "You already played a {carta} card this turn",
      "sacaConPotencia": "{carta} serves with a power of {valor}",
      "paseConPotencia": "{carta} sets with a power of {valor}",
      "remataConPotencia": "{carta} spikes with a power of {valor}",
      "recepcionVsAtaque": "Reception: {recepcion} vs Attack: {ataque}",
      "buenaRecepcion": "{carta} receives with a power of {valor} = Good reception",
      "recepcionFallida": "{carta} receives with a power of {valor} = Failed reception",
      "puntoParaRival": "Point for {jugador}",
      "defensaTotal": "Total block: {valor}",
      "bloqueoExitoso": "Block successful",
      "bloqueoFallido": "Block insufficient",
      "mulliganConfirmado": "{jugador} confirms the mulligan",
      "mulliganRival": "{jugador} mulligan — return the cards you don't want and confirm",
      "partidaIniciada": "Game started! {jugador} serves",
      "pierdePartida": "{jugador} has no cards in their point deck. They have lost the match!",
      "pierdeUnPunto": "{jugador} loses a point and draws a card from their point deck. {cantidad} remaining",
      "cartaDevuelta": "{carta} returned to the deck",
      "concedePunto": "{jugador} concedes the point",
      "efectoActivo": "Active effect: {tipo}",
      "potenciarReceptor": "Receiver boost effect: +{valor} to {carta} reception",
      "potenciarColocador": "Setter boost effect: +{valor} to {carta} set",
      "potenciarRematador": "Spiker boost effect: +{valor} to {carta} spike",
      "potenciarReceptorEscuela": "Active effect: receivers{escuela} get +{valor} to reception",
      "potenciarColocadorEscuela": "Active effect: setters{escuela} get +{valor} to set",
      "potenciarRematadorEscuela": "Active effect: spikers{escuela} get +{valor} to spike",
      "potenciarPersonajeActivo": "Active effect: {nombre} will get +{valor} to {zona} this turn",
      "potenciarPersonaje": "Effect: +{valor} to {zona} for {nombre}",
      "efectoDebilitarReceptor": "Effect: -{valor} to {carta} reception",
      "efectoDebilitarColocador": "Effect weakened setter: -{valor} to {carta} set",
      "efectoDebilitarRematador": "Effect weakened spiker: -{valor} to {carta} spike",
      "efectoDebilitarBloqueo": "Effect: -{valor} to {carta} block",
      "debilitarRematadorActivo": "Active effect: next rival spiker will have -{valor} to spike",
      "debilitarColocadorActivo": "Active effect: next rival setter will have -{valor} to set",
      "debilitarReceptorActivo": "Active effect: next rival receiver will have -{valor} to reception",
      "debilitarBloqueadorCentralActivo": "Active effect: next rival central blocker will have -{valor} to block",
      "efectoTendo": "Tendo effect: rival draws 1 card each time you add a card to your hand",
      "blockoutActivo": "Active effect: rival blockers with block equal or less than {valor} go to discard",
      "blockout": "Blockout: {carta} has block equal or less than {valor} and goes to discard",
      "efectoBloqueoOfensivo": "Offensive Block ({valor}) effect: if block is successful the counterattack will have a power of {valor}",
      "anularBloqueadorCentralActivo": "Active effect: rival central blocker will have their block nullified",
      "anularBloqueadorCentral": "Active effect: central blocker block nullified",
      "negarBloqueadoresApoyoActivo": "Active effect: rival can only place the central blocker this turn",
      "negarBloqueadoresApoyo": "You cannot place support blockers this turn",
      "negarReceptorAltoActivo": "Active effect: rival cannot place a receiver with base reception of 6 or more",
      "negarReceptorAlto": "You cannot place a receiver with reception of 6 or more this turn",
      "negarColocadorActivo": "Active effect: rival cannot place a setter next turn",
      "negarColocador": "You cannot place a setter this turn",
      "negarOneTouchActivo": "Active effect: rival cannot use One Touch in their next block",
      "negarOneTouch": "One Touch negated by rival ability",
      "negarCartaDesdeManoActivo": "Active effect: rival cannot use hand abilities in {fases}",
      "negarCartaDesdeMano": "You cannot use hand abilities in {fases}",
      "negarEventosActivo": "Active effect: rival cannot play {fase} events",
      "negarEventos": "You cannot play {fase} events this turn",
      "negarRobar": "Active effect: {jugador} cannot draw cards by ability this turn",
      "anularHabilidadReceptorActivo": "Active effect: next rival receiver cannot use their ability",
      "anularHabilidadReceptor": "The receiver cannot use their ability this turn",
      "anularHabilidadColocador": "Active effect: setter cannot use their ability",
      "limitarBloqueadoresActivo": "Active effect: rival can only place up to {max} blockers",
      "limitarBloqueadores": "You cannot place more than {max} blockers this turn",
      "maximoBloqueadores": "Maximum 2 support blockers",
      "bloqueoMinimoActivo": "Active effect: rival block will fail if total defense is {valor} or less",
      "bloqueoMinimo": "Minimum block effect: insufficient block forced",
      "oneTouch": "One Touch ({valor}): -{valor} to rival attack. Current attack: {ataque}",
      "bloqueoOfensivo": "Offensive block: counterattack has power {valor}",
      "mazoPuntosPreparado": "{jugador}: point deck prepared with 2 cards",
      "cartaColocadaBloqueo": "{jugador} plays {carta} as {tipo} ({stat})",
      "bloqueadorCentral": "Central blocker",
      "apoyoBloqueo": "Support blocker",
      "soloDesdeMano": "This card can only use its ability from hand",
      "noHabilidadMano": "This card has no hand ability",
      "noHabilidadEnFase": "You cannot use this ability in {zona} phase",
      "finta": "Feint: attack is set to {valor}. Block phase is skipped",
      "robarCuandoRival": "Rival draws 1 card by effect",
      "robarCuandoRivalActivo": "Active effect: rival draws 1 card each time you add a card to your hand",
      "negarRobarActivo": "Active effect: rival cannot draw cards through abilities next turn",
      "sinCartasValidas": "No valid cards found",
      "esperandoDescarte": "Waiting for rival to discard a card",
      "descartarCuandoRoboActivo": "Active effect: rival must discard 1 card each time they add a card to their hand by non-standard means",
      "cartaColocadaComoRematador": "{carta} placed as spiker with +{valor} to spike",
      "habilidadActivada": "{carta} ability activated",
      "condicionNoCumplida": "Condition not met",
      "condicionCumplida": "Additional condition met. Effect activated",
      "cartaDescartadaCoste": "{carta} discarded as cost",
      "cartaRevelada": "Card revealed: {carta}",
      "cartasAlFondoMazo": "Remaining cards sent to the bottom of the deck",
      "motivar": "Motivation: you draw 1 extra card from the rival's point",
      "motivarActivo": "Active effect: if the rival loses a point next turn, you draw 1 extra card"
    }
  },
  "fr": {
    "log": {
      "noEsTuTurno": "Ce n’est pas ton tour",
      "mulliganPrimero": "Il faut d’abord résoudre le mulligan",
      "soloMulligan": "Tu en peux retourner des cartes que pendant le mulligan",
      "seleccionaCarta": "Sélectionne une carte d’abord",
      "seleccionaCartaMulligan": "Sélectionne une carte à remettre dans le deck",
      "cartaSeleccionadaCampo": "Carte sélectionnée : {carta}",
      "mulliganYaConfirmado": "Le mulligan a été déjà confirmé",
      "noEsFase": "Ce n'est pas la phase de {zona}",
      "noEsFaseRecepcion": "Ce n’est pas la phase de réception",
      "noEsFasePase": "Ce n'est pas la phase de passe",
      "noEsFaseRemate": "Ce n'est pas la phase d'attaque",
      "noEsFaseBloqueo": "Ce n'est pas la phase de bloc",
      "noCartaEnZona": "Aucune carte jouée ce tour en {zona}",
      "eventoUsarBoton": "Les événements se jouent avec le bouton Jouer Événement",
      "zonaProhibida": "{carta} ne peut pas jouer en {zona}",
      "cartaDuplicada": "Tu as déjà joué {carta} ce tour",
      "noColocador": "Tu ne peux pas placer un passeur (S) ce tour",
      "yaHayCartaEnZona": "Il y a déjà une carte en {zona}",
      "cartaColocadaEn": "{jugador} joue {carta} en {zona} ({stat})",
      "noReceptorAlto": "Tu ne peux pas placer un receveur avec réception 6 ou plus ce tour",
      "sinCartasEnMazo": "{jugador} n'a plus de cartes dans le deck",
      "robarCartas": "{jugador} pioche {cantidad} carte(s)",
      "gutsInsuficiente": "Pas assez de cartes dans la zone GUTS indiquée",
      "gutsInsuficienteMultiZona": "Pas assez de GUTS sur le terrain (besoin de {cantidad}, vous en avez {total})",
      "gutsUsado": "GUTS utilisé correctement en {zona}",
      "gutsMultiZona": "GUTS : {cantidad} cartes envoyées à la défausse",
      "gutsTitulo": "GUTS en {zona} : Défaussez ( {actual} / {total} )",
      "cartaEnGuts": "Cette carte est dans le GUTS et ne peut pas utiliser sa capacité",
      "sinHabilidad": "Cette carte n'a pas de capacité",
      "habilidadYaUsada": "Cette capacité a déjà été utilisée",
      "noEsEvento": "Cette carte n'est pas un événement",
      "eventoFaseIncorrecta": "Tu ne peux pas jouer cet événement en phase {zona}",
      "eventoJugado": "{jugador} joue l'événement : {carta}",
      "eventoEnMano": "Tu as besoin d'une carte événement en main",
      "eventoPagar": "Carte événement envoyée à la défausse comme coût",
      "cartaUnica": "Tu as déjà joué une carte {carta} ce tour",
      "sacaConPotencia": "{carta} sert avec une puissance de {valor}",
      "paseConPotencia": "{carta} effectue une passe avec une puissance de {valor}",
      "remataConPotencia": "{carta} attaque avec une puissance de {valor}",
      "recepcionVsAtaque": "Réception : {recepcion} vs Attaque : {ataque}",
      "buenaRecepcion": "{carta} reçoit avec une puissance de {valor} = Bonne réception",
      "recepcionFallida": "{carta} reçoit avec une puissance de {valor} = Réception ratée",
      "puntoParaRival": "Point pour {jugador}",
      "defensaTotal": "Bloc total : {valor}",
      "bloqueoExitoso": "Bloc réussi",
      "bloqueoFallido": "Bloc insuffisant",
      "mulliganConfirmado": "{jugador} confirme le mulligan",
      "mulliganRival": "Mulligan de {jugador} — retourne les cartes que tu ne veux pas et confirme",
      "partidaIniciada": "Partie lancée ! {jugador} sert",
      "pierdePartida": "{jugador} n'a plus de cartes dans son deck de points. Il a perdu le match !",
      "pierdeUnPunto": "{jugador} perd un point et pioche une carte de son deck de points. Il en reste {cantidad}",
      "cartaDevuelta": "{carta} remise dans le deck",
      "concedePunto": "{jugador} concède le point",
      "efectoActivo": "Effet actif : {tipo}",
      "potenciarReceptor": "Effet boost receveur : +{valor} à la réception de {carta}",
      "potenciarColocador": "Effet boost passeur : +{valor} à la passe de {carta}",
      "potenciarRematador": "Effet boost attaquant : +{valor} à l'attaque de {carta}",
      "potenciarReceptorEscuela": "Effet actif : receveurs{escuela} auront +{valor} à la réception",
      "potenciarColocadorEscuela": "Effet actif : passeurs{escuela} auront +{valor} à la passe",
      "potenciarRematadorEscuela": "Effet actif : attaquants{escuela} auront +{valor} à l'attaque",
      "potenciarPersonajeActivo": "Effet actif : {nombre} aura +{valor} en {zona} ce tour",
      "potenciarPersonaje": "Effet : +{valor} en {zona} pour {nombre}",
      "efectoDebilitarReceptor": "Effet : -{valor} à la réception de {carta}",
      "efectoDebilitarColocador": "Effet passeur affaibli : -{valor} à la passe de {carta}",
      "efectoDebilitarRematador": "Effet attaquant affaibli : -{valor} à l'attaque de {carta}",
      "efectoDebilitarBloqueo": "Effet : -{valor} au bloc de {carta}",
      "debilitarRematadorActivo": "Effet actif : le prochain attaquant rival aura -{valor} à l'attaque",
      "debilitarColocadorActivo": "Effet actif : le prochain passeur rival aura -{valor} à la passe",
      "debilitarReceptorActivo": "Effet actif : le prochain receveur rival aura -{valor} à la réception",
      "debilitarBloqueadorCentralActivo": "Effet actif : le prochain bloqueur central rival aura -{valor} au bloc",
      "efectoTendo": "Effet Tendo : le rival pioche 1 carte chaque fois que tu ajoutes une carte à ta main",
      "blockoutActivo": "Effet actif : les bloqueurs rivaux avec bloc inférieur ou égal à {valor} vont à la défausse",
      "blockout": "Blockout : {carta} a un bloc inférieur ou égal à {valor} et va à la défausse",
      "efectoBloqueoOfensivo": "Effet Bloc Offensif ({valor}) : si le bloc est réussi le contre-attaque aura une puissance de {valor}",
      "anularBloqueadorCentralActivo": "Effet actif : le bloqueur central rival aura son bloc annulé",
      "anularBloqueadorCentral": "Effet actif : bloc du bloqueur central annulé",
      "negarBloqueadoresApoyoActivo": "Effet actif : le rival ne peut placer que le bloqueur central ce tour",
      "negarBloqueadoresApoyo": "Tu ne peux pas placer de bloqueurs de soutien ce tour",
      "negarReceptorAltoActivo": "Effet actif : le rival ne pourra pas placer un receveur avec réception de base de 6 ou plus",
      "negarReceptorAlto": "Tu ne peux pas placer un receveur avec réception de 6 ou plus ce tour",
      "negarColocadorActivo": "Effet actif : le rival ne pourra pas placer un passeur au prochain tour",
      "negarColocador": "Tu ne peux pas placer un passeur ce tour",
      "negarOneTouchActivo": "Effet actif : le rival ne pourra pas utiliser One Touch dans son prochain bloc",
      "negarOneTouch": "One Touch annulé par la capacité du rival",
      "negarCartaDesdeManoActivo": "Effet actif : le rival ne pourra pas utiliser de capacités depuis la main en {fases}",
      "negarCartaDesdeMano": "Tu ne peux pas utiliser de capacités depuis la main en {fases}",
      "negarEventosActivo": "Effet actif : le rival ne pourra pas jouer d'événements de {fase}",
      "negarEventos": "Tu ne peux pas jouer d'événements de {fase} ce tour",
      "negarRobar": "Effet actif : {jugador} ne peut pas piocher de cartes par capacité ce tour",
      "anularHabilidadReceptorActivo": "Effet actif : le prochain receveur rival ne pourra pas utiliser sa capacité",
      "anularHabilidadReceptor": "Le receveur ne peut pas utiliser sa capacité ce tour",
      "anularHabilidadColocador": "Effet actif : le passeur ne peut pas utiliser sa capacité",
      "limitarBloqueadoresActivo": "Effet actif : le rival ne pourra placer que {max} bloqueurs",
      "limitarBloqueadores": "Tu ne peux pas placer plus de {max} bloqueurs ce tour",
      "maximoBloqueadores": "Maximum 2 bloqueurs de soutien",
      "bloqueoMinimoActivo": "Effet actif : le bloc rival échouera si la défense totale est {valor} ou moins",
      "bloqueoMinimo": "Effet de bloc minimum : bloc insuffisant forcé",
      "oneTouch": "One Touch ({valor}) : -{valor} à l'attaque rivale. Attaque actuel : {ataque}",
      "bloqueoOfensivo": "Bloc offensif : le contre-attaque a une puissance de {valor}",
      "mazoPuntosPreparado": "{jugador} : deck de points préparé avec 2 cartes",
      "cartaColocadaBloqueo": "{jugador} joue {carta} en tant que {tipo} ({stat})",
      "bloqueadorCentral": "Bloqueur central",
      "apoyoBloqueo": "Bloqueur de soutien",
      "soloDesdeMano": "Cette carte ne peut utiliser sa capacité que depuis la main",
      "noHabilidadMano": "Cette carte n'a pas de capacité depuis la main",
      "noHabilidadEnFase": "Tu ne peux pas utiliser cette capacité en phase {zona}",
      "finta": "Feinte : l'attaque est fixée à {valor}. La phase de bloc est ignorée",
      "robarCuandoRival": "Le rival pioche 1 carte par effet",
      "robarCuandoRivalActivo": "Effet actif : le rival pioche 1 carte chaque fois que tu ajoutes une carte à ta main",
      "negarRobarActivo": "Effet actif : le rival ne pourra pas piocher de cartes via des capacités au prochain tour",
      "sinCartasValidas": "Aucune carte valide trouvée",
      "esperandoDescarte": "En attente que le rival se défausse d'une carte",
      "descartarCuandoRoboActivo": "Effet actif : le rival devra se défausser d'1 carte chaque fois qu'il ajoute une carte à sa main par des moyens non standard",
      "cartaColocadaComoRematador": "{carta} placé comme attaquant avec +{valor} à l'attaque",
      "habilidadActivada": "Capacité de {carta} activée",
      "condicionNoCumplida": "Condition non remplie",
      "condicionCumplida": "Condition supplémentaire remplie. Effet activé",
      "cartaDescartadaCoste": "{carta} défaussée comme coût",
      "cartaRevelada": "Carte révélée : {carta}",
      "cartasAlFondoMazo": "Cartes restantes envoyées au fond du deck",
      "motivar": "Motivation : tu pioches 1 carte supplémentaire grâce au point du rival",
      "motivarActivo": "Effet actif : si le rival perd un point au prochain tour, tu pioches 1 carte supplémentaire"
    }
  },
  "": {
    "log": {
      "noEsTuTurno": "",
      "mulliganPrimero": "",
      "soloMulligan": "",
      "seleccionaCarta": "",
      "seleccionaCartaMulligan": "",
      "cartaSeleccionadaCampo": "",
      "mulliganYaConfirmado": "",
      "noEsFase": "",
      "noEsFaseRecepcion": "",
      "noEsFasePase": "",
      "noEsFaseRemate": "",
      "noEsFaseBloqueo": "",
      "noCartaEnZona": "",
      "eventoUsarBoton": "",
      "zonaProhibida": "",
      "cartaDuplicada": "",
      "noColocador": "",
      "yaHayCartaEnZona": "",
      "cartaColocadaEn": "",
      "noReceptorAlto": "Por ver si dejo o no",
      "sinCartasEnMazo": "",
      "robarCartas": "",
      "gutsInsuficiente": "",
      "gutsInsuficienteMultiZona": "",
      "gutsUsado": "",
      "gutsMultiZona": "",
      "gutsTitulo": "",
      "cartaEnGuts": "",
      "sinHabilidad": "",
      "habilidadYaUsada": "",
      "noEsEvento": "",
      "eventoFaseIncorrecta": "",
      "eventoJugado": "",
      "eventoEnMano": "",
      "eventoPagar": "",
      "cartaUnica": "",
      "sacaConPotencia": "",
      "paseConPotencia": "",
      "remataConPotencia": "",
      "recepcionVsAtaque": "",
      "buenaRecepcion": "",
      "recepcionFallida": "",
      "puntoParaRival": "",
      "defensaTotal": "",
      "bloqueoExitoso": "",
      "bloqueoFallido": "",
      "mulliganConfirmado": "",
      "mulliganRival": "",
      "partidaIniciada": "",
      "pierdePartida": "",
      "pierdeUnPunto": "",
      "cartaDevuelta": "",
      "concedePunto": "",
      "efectoActivo": "",
      "potenciarReceptor": "",
      "potenciarColocador": "",
      "potenciarRematador": "",
      "potenciarReceptorEscuela": "",
      "potenciarColocadorEscuela": "",
      "potenciarRematadorEscuela": "",
      "potenciarPersonajeActivo": "",
      "potenciarPersonaje": "",
      "efectoDebilitarReceptor": "",
      "efectoDebilitarColocador": "",
      "efectoDebilitarRematador": "",
      "efectoDebilitarBloqueo": "",
      "debilitarRematadorActivo": "",
      "debilitarColocadorActivo": "",
      "debilitarReceptorActivo": "",
      "debilitarBloqueadorCentralActivo": "",
      "efectoTendo": "",
      "blockoutActivo": "",
      "blockout": "",
      "efectoBloqueoOfensivo": "",
      "anularBloqueadorCentralActivo": "",
      "anularBloqueadorCentral": "",
      "negarBloqueadoresApoyoActivo": "",
      "negarBloqueadoresApoyo": "",
      "negarReceptorAltoActivo": "",
      "negarReceptorAlto": "",
      "negarColocadorActivo": "",
      "negarColocador": "",
      "negarOneTouchActivo": "",
      "negarOneTouch": "",
      "negarCartaDesdeManoActivo": "",
      "negarCartaDesdeMano": "",
      "negarEventosActivo": "",
      "negarEventos": "",
      "negarRobar": "",
      "anularHabilidadReceptorActivo": "",
      "anularHabilidadReceptor": "",
      "anularHabilidadColocador": "",
      "limitarBloqueadoresActivo": "",
      "limitarBloqueadores": "",
      "maximoBloqueadores": "",
      "bloqueoMinimoActivo": "",
      "bloqueoMinimo": "",
      "oneTouch": "",
      "bloqueoOfensivo": "",
      "mazoPuntosPreparado": "",
      "cartaColocadaBloqueo": "",
      "bloqueadorCentral": "",
      "apoyoBloqueo": "",
      "soloDesdeMano": "",
      "noHabilidadMano": "",
      "noHabilidadEnFase": "",
      "finta": "",
      "robarCuandoRival": "",
      "robarCuandoRivalActivo": "",
      "negarRobarActivo": "",
      "sinCartasValidas": "",
      "esperandoDescarte": "",
      "descartarCuandoRoboActivo": "",
      "cartaColocadaComoRematador": "",
      "habilidadActivada": "",
      "condicionNoCumplida": "",
      "condicionCumplida": "",
      "cartaDescartadaCoste": "",
      "cartaRevelada": "",
      "cartasAlFondoMazo": "",
      "motivar": "",
      "motivarActivo": ""
    }
  }
};