// Generado automáticamente — no editar manualmente
// Editar el archivo traducciones.csv y volver a convertir

const TRADUCCIONES = {
  "es": {
    "log": {
      "noEsTuTurno": "No es tu turno",
      "mulliganPrimero": "Primero hay que resolver el mulligan",
      "soloMulligan": "Sólo puedes devolver cartas durante el mulligan",
      "seleccionaCarta": "Selecciona una carta primero",
      "seleccionaCartaMulligan": "Selecciona una carta para devolver al mazo",
      "mulliganYaConfirmado": "El mulligan ya ha sido confirmado",
      "noEsFaseRecepcion": "No es fase de recepción",
      "noEsFasePase": "No es fase de pase",
      "noEsFaseRemate": "No es fase de remate",
      "noEsFaseBloqueo": "No es fase de bloqueo",
      "noCartaEnZona": "No has jugado ninguna carta este turno en {zona}",
      "eventoUsarBoton": "Los eventos se juegan con el botón Jugar Evento",
      "zonaProhibida": "{carta} no puede jugar en {zona}",
      "cartaDuplicada": "Ya has jugado a {carta} este turno",
      "noColocador": "No puedes colocar un colocador (S) este turno",
      "yaHayCartaEnZona": "Ya hay una carta en {zona}",
      "cartaColocadaEn": "{jugador} juega a {carta} en {zona}",
      "noReceptorAlto": "No puedes colocar un receptor con recepción de 6 o más este turno",
      "sinCartasEnMazo": "{jugador} no tiene más cartas en el mazo",
      "robarCartas": "{jugador} roba {cantidad} carta(s)",
      "gutsInsuficiente": "No hay suficientes cartas en la zona de GUTS indicada",
      "gutsUsado": "GUTS usado correctamente en {zona}",
      "gutsTitulo": "GUTS en {zona}: </br>Descarta ( {actual} / {total} )",
      "sacaConPotencia": "{carta} saca con una potencia de {valor}",
      "paseConPotencia": "{carta} realiza un pase con una potencia de {valor}",
      "remataConPotencia": "{carta} remata con una potencia de {valor}",
      "recepcionVsAtaque": "Recepción: {recepcion} vs Ataque: {ataque}",
      "buenaRecepcion": "{carta} recibe con una potencia de {valor} = Buena recepción",
      "recepcionFallida": "{carta} recibe con una potencia de {valor} = Recepción fallida",
      "puntoParaRival": "Punto para {jugador}",
      "defensaTotal": "Defensa total: {valor}",
      "bloqueoExitoso": "Bloqueo exitoso",
      "bloqueoFallido": "Bloqueo insuficiente",
      "mulliganConfirmado": "{jugador} confirma el mulligan",
      "mulliganRival": "Mulligan de {jugador} — devuelve las cartas que no quieras y confirma",
      "partidaIniciada": "¡Partida iniciada! Saca {jugador}",
      "pierdePartida": "{jugador} no tiene cartas en su mazo de puntos. ¡Ha perdido el partido!",
      "pierdeUnPunto": "{jugador} pierde un punto y roba una carta de su mazo de puntos. Le quedan {cantidad}",
      "cartaDevuelta": "{carta} devuelta al mazo",
      "concedePunto": "{jugador} concede el punto",
      "efectoActivo": "Efecto activo: {tipo}",
      "efectoDebilitarReceptor": "Efecto: -{valor} a la recepción de {carta}",
      "efectoDebilitarColocador": "Efecto colocador debilitado: -{valor} al pase de {carta}",
      "efectoDebilitarRematador": "Efecto rematador debilitado: -{valor} al remate de {carta}",
      "efectoKageyamaSP": "Efecto Kageyama: Hinata sumará +2 al remate este turno",
      "efectoTendo": "Efecto Tendo: el rival robará 1 carta cada vez que añadas una carta a tu mano",
      "efectoBlockout": "Efecto Blockout({valor}): bloqueadores rivales con bloqueo menor o igual a {valor} irán al trash",
      "efectoBloqueoOfensivo": "Efecto de Bloqueo Ofensivo ({valor}): si el bloqueo es exitoso el contraataque tendrá una potencia de {valor}",
      "efectoBloqueoMinimo": "Efecto activo: el bloqueo rival fallará si su defensa total es {valor} o menos",
      "efectoAnularBloqueadorCentral": "Efecto activo: bloqueo del bloqueador central anulado",
      "negarBloqueadoresApoyo": "Efecto: el rival solo puede colocar al bloqueador central este turno",
      "negarReceptorAlto": "Efecto: el rival no puede colocar un receptor con recepción original de 6 o más",
      "negarColocador": "Efecto activo: el rival no podrá jugar un colocador el próximo turno",
      "negarOneTouch": "Efecto activo: el rival no podrá usar One Touch en su próximo bloqueo",
      "negarCartaDesdeMano": "Efecto activo: el rival no podrá usar habilidades desde la mano en {fases}",
      "negarEventosBloqueo": "Efecto activo: el rival no podrá jugar eventos de bloqueo",
      "anularHabilidadReceptor": "Efecto activo: el siguiente receptor rival no podrá usar su habilidad",
      "limitarBloqueadores": "Efecto: el rival solo puede colocar hasta {max} bloqueadores",
      "blockoutTrash": "Blockout: {carta} tiene bloqueo menor o igual a {valor} y va al trash"
    }
  },
  "en": {
    "log": {
      "noEsTuTurno": "Is not your turn",
      "mulliganPrimero": "Mulligan must be resolved first",
      "soloMulligan": "You can only return cards during mulligan",
      "seleccionaCarta": "Select a card first",
      "seleccionaCartaMulligan": "Select a card to return to the deck",
      "mulliganYaConfirmado": "Mulligan already confirmed",
      "noEsFaseRecepcion": "Not the reception phase",
      "noEsFasePase": "Not the set phase",
      "noEsFaseRemate": "Not the spike phase",
      "noEsFaseBloqueo": "Not the block phase",
      "noCartaEnZona": "No card played this turn in {zona}",
      "eventoUsarBoton": "Events are played with the Play Event button",
      "zonaProhibida": "{carta} cannot play in {zona}",
      "cartaDuplicada": "You already played {carta} this turn",
      "noColocador": "You cannot place a setter (S) this turn",
      "yaHayCartaEnZona": "There is already a card in {zona}",
      "cartaColocadaEn": "{jugador} plays {carta} in {zona}",
      "noReceptorAlto": "You cannot place a receiver with reception 6 or more this turn",
      "sinCartasEnMazo": "{jugador} has no more cards in the deck",
      "robarCartas": "{jugador} draws {cantidad} card(s)",
      "gutsInsuficiente": "Not enough cards in the indicated GUTS zone",
      "gutsUsado": "GUTS used correctly in {zona}",
      "gutsTitulo": "GUTS in {zona}: </br>Discard ( {actual} / {total} )",
      "sacaConPotencia": "{carta} serves with a power of {valor}",
      "paseConPotencia": "{carta} sets with a power of {valor}",
      "remataConPotencia": "{carta} spikes with a power of {valor}",
      "recepcionVsAtaque": "Reception: {recepcion} vs Attack: {ataque}",
      "buenaRecepcion": "{carta} receives with a power of {valor} = Good reception",
      "recepcionFallida": "{carta} receives with a power of {valor} = Failed reception",
      "puntoParaRival": "Point for {jugador}",
      "defensaTotal": "Total defense: {valor}",
      "bloqueoExitoso": "Block successful",
      "bloqueoFallido": "Block insufficient",
      "mulliganConfirmado": "{jugador} confirms the mulligan",
      "mulliganRival": "{jugador} mulligan — return the cards you don't want and confirm",
      "partidaIniciada": "Game started! {jugador} serves",
      "pierdePartida": "{jugador} has no cards in their point deck. They have lost the match!",
      "pierdeUnPunto": "{jugador} loses a point and draws a card from their point deck. {cantidad} remaining",
      "cartaDevuelta": "{carta} returned to the deck",
      "concedePunto": "{jugador} concedes the point",
      "efectoActivo": "Active effect: {tipo}",
      "efectoDebilitarReceptor": "Effect: -{valor} to {carta} reception",
      "efectoDebilitarColocador": "Effect weakened setter: -{valor} to {carta} set",
      "efectoDebilitarRematador": "Effect weakened spiker: -{valor} to {carta} spike",
      "efectoKageyamaSP": "Kageyama effect: Hinata gets +2 to spike this turn",
      "efectoTendo": "Tendo effect: rival draws 1 card each time you add a card to your hand",
      "efectoBlockout": "Blockout({valor}) effect: rival blockers with block equal or less than {valor} go to discard",
      "efectoBloqueoOfensivo": "Offensive Block ({valor}) effect: if block is successful the counterattack will have a power of {valor}",
      "efectoBloqueoMinimo": "Active effect: rival block will fail if total defense is {valor} or less",
      "efectoAnularBloqueadorCentral": "Active effect: central blocker block nullified",
      "negarBloqueadoresApoyo": "Effect: rival can only place the central blocker this turn",
      "negarReceptorAlto": "Effect: rival cannot place a receiver with base reception of 6 or more",
      "negarColocador": "Active effect: rival cannot place a setter next turn",
      "negarOneTouch": "Active effect: rival cannot use One Touch in their next block",
      "negarCartaDesdeMano": "Active effect: rival cannot use hand abilities in {fases}",
      "negarEventosBloqueo": "Active effect: rival cannot play block events",
      "anularHabilidadReceptor": "Active effect: next rival receiver cannot use their ability",
      "limitarBloqueadores": "Effect: rival can only place up to {max} blockers",
      "blockoutTrash": "Blockout: {carta} has block equal or less than {valor} and goes to discard"
    }
  },
  "fr": {
    "log": {
      "noEsTuTurno": "Ce n’est pas ton tour",
      "mulliganPrimero": "Il faut d’abord résoudre le mulligan",
      "soloMulligan": "Tu en peux retourner des cartes que pendant le mulligan",
      "seleccionaCarta": "Sélectionne une carte d’abord",
      "seleccionaCartaMulligan": "Sélectionne une carte à remettre dans le deck",
      "mulliganYaConfirmado": "Le mulligan a été déjà confirmé",
      "noEsFaseRecepcion": "Ce n’est pas la phase de réception",
      "noEsFasePase": "Ce n'est pas la phase de passe",
      "noEsFaseRemate": "Ce n'est pas la phase d'attaque",
      "noEsFaseBloqueo": "Ce n'est pas la phase de bloc",
      "noCartaEnZona": "Aucune carte jouée ce tour en {zona}",
      "eventoUsarBoton": "Les événements se jouent avec le bouton Jouer Événement",
      "zonaProhibida": "{carta} ne peut pas jouer en {zona}",
      "cartaDuplicada": "Tu as déjà joué {carta} ce tour",
      "noColocador": "Tu ne peux pas placer un passeur (S) ce tour",
      "yaHayCartaEnZona": "Il y a déjà une carte en {zona}",
      "cartaColocadaEn": "{jugador} joue {carta} en {zona}",
      "noReceptorAlto": "Tu ne peux pas placer un receveur avec réception 6 ou plus ce tour",
      "sinCartasEnMazo": "{jugador} n'a plus de cartes dans le deck",
      "robarCartas": "{jugador} pioche {cantidad} carte(s)",
      "gutsInsuficiente": "Pas assez de cartes dans la zone GUTS indiquée",
      "gutsUsado": "GUTS utilisé correctement en {zona}",
      "gutsTitulo": "GUTS en {zona} : </br>Défaussez ( {actual} / {total} )",
      "sacaConPotencia": "{carta} sert avec une puissance de {valor}",
      "paseConPotencia": "{carta} effectue une passe avec une puissance de {valor}",
      "remataConPotencia": "{carta} attaque avec une puissance de {valor}",
      "recepcionVsAtaque": "Réception : {recepcion} vs Attaque : {ataque}",
      "buenaRecepcion": "{carta} reçoit avec une puissance de {valor} = Bonne réception",
      "recepcionFallida": "{carta} reçoit avec une puissance de {valor} = Réception ratée",
      "puntoParaRival": "Point pour {jugador}",
      "defensaTotal": "Défense totale : {valor}",
      "bloqueoExitoso": "Bloc réussi",
      "bloqueoFallido": "Bloc insuffisant",
      "mulliganConfirmado": "{jugador} confirme le mulligan",
      "mulliganRival": "Mulligan de {jugador} — retourne les cartes que tu ne veux pas et confirme",
      "partidaIniciada": "Partie lancée ! {jugador} sert",
      "pierdePartida": "{jugador} n'a plus de cartes dans son deck de points. Il a perdu le match !",
      "pierdeUnPunto": "{jugador} perd un point et pioche une carte de son deck de points. Il en reste {cantidad}",
      "cartaDevuelta": "{carta} remise dans le deck",
      "concedePunto": "{jugador} concède le point",
      "efectoActivo": "Effet actif : {tipo}",
      "efectoDebilitarReceptor": "Effet : -{valor} à la réception de {carta}",
      "efectoDebilitarColocador": "Effet passeur affaibli : -{valor} à la passe de {carta}",
      "efectoDebilitarRematador": "Effet attaquant affaibli : -{valor} à l'attaque de {carta}",
      "efectoKageyamaSP": "Effet Kageyama : Hinata gagne +2 à l'attaque ce tour",
      "efectoTendo": "Effet Tendo : le rival pioche 1 carte chaque fois que tu ajoutes une carte à ta main",
      "efectoBlockout": "Effet Blockout({valor}) : les bloqueurs rivaux avec bloc inférieur ou égal à {valor} vont à la défausse",
      "efectoBloqueoOfensivo": "Effet Bloc Offensif ({valor}) : si le bloc est réussi le contre-attaque aura une puissance de {valor}",
      "efectoBloqueoMinimo": "Effet actif : le bloc rival échouera si la défense totale est {valor} ou moins",
      "efectoAnularBloqueadorCentral": "Effet actif : bloc du bloqueur central annulé",
      "negarBloqueadoresApoyo": "Effet : le rival ne peut placer que le bloqueur central ce tour",
      "negarReceptorAlto": "Effet : le rival ne peut pas placer un receveur avec réception de base de 6 ou plus",
      "negarColocador": "Effet actif : le rival ne pourra pas placer un passeur au prochain tour",
      "negarOneTouch": "Effet actif : le rival ne pourra pas utiliser One Touch dans son prochain bloc",
      "negarCartaDesdeMano": "Effet actif : le rival ne pourra pas utiliser de capacités depuis la main en {fases}",
      "negarEventosBloqueo": "Effet actif : le rival ne pourra pas jouer d'événements de bloc",
      "anularHabilidadReceptor": "Effet actif : le prochain receveur rival ne pourra pas utiliser sa capacité",
      "limitarBloqueadores": "Effet : le rival ne peut placer que {max} bloqueurs",
      "blockoutTrash": "Blockout : {carta} a un bloc inférieur ou égal à {valor} et va à la défausse"
    }
  },
  "": {
    "log": {
      "noEsTuTurno": "",
      "mulliganPrimero": "",
      "soloMulligan": "",
      "seleccionaCarta": "",
      "seleccionaCartaMulligan": "",
      "mulliganYaConfirmado": "",
      "noEsFaseRecepcion": "",
      "noEsFasePase": "",
      "noEsFaseRemate": "",
      "noEsFaseBloqueo": "",
      "noCartaEnZona": "",
      "eventoUsarBoton": "",
      "zonaProhibida": "",
      "cartaDuplicada": "",
      "noColocador": "",
      "yaHayCartaEnZona": "",
      "cartaColocadaEn": "",
      "noReceptorAlto": "Por ver si dejo o no",
      "sinCartasEnMazo": "",
      "robarCartas": "",
      "gutsInsuficiente": "",
      "gutsUsado": "",
      "gutsTitulo": "",
      "sacaConPotencia": "",
      "paseConPotencia": "",
      "remataConPotencia": "",
      "recepcionVsAtaque": "",
      "buenaRecepcion": "",
      "recepcionFallida": "",
      "puntoParaRival": "",
      "defensaTotal": "",
      "bloqueoExitoso": "",
      "bloqueoFallido": "",
      "mulliganConfirmado": "",
      "mulliganRival": "",
      "partidaIniciada": "",
      "pierdePartida": "",
      "pierdeUnPunto": "",
      "cartaDevuelta": "",
      "concedePunto": "",
      "efectoActivo": "",
      "efectoDebilitarReceptor": "",
      "efectoDebilitarColocador": "",
      "efectoDebilitarRematador": "",
      "efectoKageyamaSP": "",
      "efectoTendo": "",
      "efectoBlockout": "",
      "efectoBloqueoOfensivo": "",
      "efectoBloqueoMinimo": "",
      "efectoAnularBloqueadorCentral": "",
      "negarBloqueadoresApoyo": "",
      "negarReceptorAlto": "",
      "negarColocador": "",
      "negarOneTouch": "",
      "negarCartaDesdeMano": "",
      "negarEventosBloqueo": "",
      "anularHabilidadReceptor": "",
      "limitarBloqueadores": "",
      "blockoutTrash": ""
    }
  }
};